{% set name = "mt-metadata" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mt_metadata-{{ version }}.tar.gz
  sha256: dd65597c28d5adc34a311011b946b6adfef455761b793c01d09d14267319a6b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.10
  run:
    - python >=3.10
    - numpy
    - pandas
    - pyyaml
    - obspy
    - matplotlib-base
    - xarray
    - loguru
    - pydantic
    - pyproj
    - typing-extensions

test:
  imports:
    - mt_metadata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kujaku11/mt_metadata
  summary: Metadata for magnetotelluric data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kujaku11
    - kkappler
    - lheagy
