{% set name = "mt-metadata" %}
{% set version = "0.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mt_metadata-{{ version }}.tar.gz
  sha256: cf8384c68a8c4329b7544d3d28a5382a1aad3cd1d07e5842d82c42f82d007c58

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.5
  run:
    - concurrent-log-handler
    - matplotlib-base
    - numpy <=1.21
    - obspy
    - pandas
    - python >=3.5
    - pyyaml
    - xarray

test:
  imports:
    - mt_metadata
    - mt_metadata.base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kujaku11/mt_metadata
  summary: Metadata for magnetotelluric data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kujaku11
    - jp
