{% set name = "mt-metadata" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mt_metadata-{{ version }}.tar.gz
  sha256: 7b07c5d10b3bc08d6c8e300c873b34351bbfe6e73de595aaeb2b9770c8b1f4ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - pytest-runner
    - pip
  run:
    - python >=3.5
    - concurrent-log-handler
    - numpy <=1.21
    - pandas
    - pyyaml
    - obspy
    - matplotlib-base
    - xarray

test:
  imports:
    - mt_metadata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kujaku11/mt_metadata
  summary: Metadata for magnetotelluric data
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - kujaku11
    - lheagy
    - kkappler
