{% set name = "mt-metadata" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mt_metadata-{{ version }}.tar.gz
  sha256: 828107cd04d0fb9f717f9f0378960d8d28c211f0b97c3da4be50a395c31a8a03

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.5
  run:
    - concurrent-log-handler
    - matplotlib-base
    - numpy <=1.21
    - obspy
    - pandas
    - python >=3.5
    - pyyaml
    - xarray

test:
  imports:
    - mt_metadata
    - mt_metadata.base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kujaku11/mt_metadata
  summary: Metadata for magnetotelluric data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kujaku11
    - kkappler
    - lheagy
