{% set name = "mt-metadata" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mt_metadata-{{ version }}.tar.gz
  sha256: 6e04a541b817473e0a5ea2d788ad08668d2ee775f02fb9aa2146c4eba0867693

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.5
  run:
    - python >=3.7
    - numpy
    - pandas <=1.5.3
    - pyyaml
    - obspy
    - matplotlib-base
    - xarray
    - loguru

test:
  imports:
    - mt_metadata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kujaku11/mt_metadata
  summary: Metadata for magnetotelluric data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kujaku11
    - kkappler
    - lheagy
