{% set name = "mt-metadata" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mt_metadata-{{ version }}.tar.gz
  sha256: 65b7c7931e2f25e274ade983874ae439058c2dce4c58dfa7428a358c0d0f1acc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pytest-runner
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas <=1.5.3
    - pyyaml
    - obspy
    - matplotlib-base
    - xarray
    - loguru

test:
  imports:
    - mt_metadata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kujaku11/mt_metadata
  summary: Metadata for magnetotelluric data
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - kujaku11
    - kkappler
    - lheagy
