{% set name = "mt-metadata" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mt_metadata-{{ version }}.tar.gz
  sha256: 2c810c1a34a756d61b3bfe2d525c8de8898c3aff38aad896f93b00aa2b1fe82b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.5
  run:
    - numpy
    - obspy
    - pandas
    - python >=3.5
    - pyyaml

test:
  imports:
    - mt_metadata
    - mt_metadata.base
    - mt_metadata.timeseries
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kujaku11/mt_metadata
  summary: Metadata for magnetotelluric data
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lheagy
    - kujaku11
    - kkappler
