{% set name = "mt-metadata" %}
{% set version = "0.3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mt_metadata-{{ version }}.tar.gz
  sha256: ce4beb241841337314a98708594debb5adb9a872aff6e53b8fd3a4f9862747ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - python >=3.7
    - numpy
    - pandas
    - pyyaml
    - obspy
    - matplotlib-base
    - xarray
    - loguru

test:
  imports:
    - mt_metadata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kujaku11/mt_metadata
  summary: Metadata for magnetotelluric data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kujaku11
    - kkappler
    - lheagy
