{% set name = "mt-metadata" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mt_metadata-{{ version }}.tar.gz
  sha256: b048a394a0ea7d3d9970398fdfe4ee8457620def96f56158d5e7613513b45df0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.5
  run:
    - numpy
    - obspy
    - pandas
    - python >=3.5
    - pyyaml
    - matplotlib-base
    - xarray
    - concurrent-log-handler

test:
  imports:
    - mt_metadata
    - mt_metadata.base
    - mt_metadata.timeseries
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kujaku11/mt_metadata
  summary: Metadata for magnetotelluric data
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lheagy
    - kujaku11
    - kkappler
